title: Kirk Brown
logo: /assets/img/United States.png
description: Seeking Data Analyst Opportunities [LinkedIn](https://www.linkedin.com/in/kirk-brown-51a830a7/)
show_downloads: true
theme: jekyll-theme-minimal
