title: Kirk Brown
        Seeking Data Analyst Opportunities
        [LinkedIn](https://www.linkedin.com/in/kirk-brown-51a830a7/)
logo: /assets/img/United States.png
description:
show_downloads: true
theme: jekyll-theme-minimal
